export {
  AkiDBClient,
  buildMemoryMetadata,
  metadataJson,
  DEFAULT_COLLECTION,
} from './client.js';
export type {
  AkiDBClientOptions,
  BatchInsertResponse,
  ClusterState,
  DeleteResponse,
  GetResult,
  HealthStatus,
  InsertResponse,
  MemoryWriteOptions,
  RawClient,
  SearchHit,
  TextSearchOptions,
  TextSearchResult,
  UpdateResponse,
  VectorInput,
} from './client.js';
export {
  AkiDBError,
  AlreadyExistsError,
  DeadlineExceededError,
  FailedPreconditionError,
  InternalError,
  InvalidArgumentError,
  NotFoundError,
  PermissionDeniedError,
  ResourceExhaustedError,
  UnauthenticatedError,
  UnavailableError,
  mapError,
} from './errors.js';
