"""AkiDB Python SDK — a typed client for the AkiDB retrieval/memory engine."""

from .client import (
    AkiDBClient,
    BatchInsertResult,
    DeleteResult,
    GetResult,
    HealthStatus,
    InsertResult,
    MemoryContext,
    MemoryScope,
    MemoryTemporal,
    SearchHit,
    TextSearchResult,
    UpdateResult,
    VectorInput,
    build_memory_metadata,
)
from .errors import (
    AkiDBError,
    AlreadyExistsError,
    DeadlineExceededError,
    FailedPreconditionError,
    InternalError,
    InvalidArgumentError,
    NotFoundError,
    PermissionDeniedError,
    ResourceExhaustedError,
    UnauthenticatedError,
    UnavailableError,
)
from .unified import (
    UnifiedRecallArtifact,
    UnifiedRecallCoordinator,
    UnifiedReplayError,
    UnifiedReplayResult,
)

__all__ = [
    "AkiDBClient",
    "BatchInsertResult",
    "DeleteResult",
    "GetResult",
    "HealthStatus",
    "InsertResult",
    "MemoryContext",
    "MemoryScope",
    "MemoryTemporal",
    "SearchHit",
    "TextSearchResult",
    "UpdateResult",
    "VectorInput",
    "build_memory_metadata",
    "AkiDBError",
    "AlreadyExistsError",
    "DeadlineExceededError",
    "FailedPreconditionError",
    "InternalError",
    "InvalidArgumentError",
    "NotFoundError",
    "PermissionDeniedError",
    "ResourceExhaustedError",
    "UnauthenticatedError",
    "UnavailableError",
    "UnifiedRecallArtifact",
    "UnifiedRecallCoordinator",
    "UnifiedReplayError",
    "UnifiedReplayResult",
]
__version__ = "1.0.0"
