# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import akidb_pb2 as akidb__pb2


class AkidbStub(object):
    """AkiDB Vector Database Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/akidb.v1.Akidb/Insert',
                request_serializer=akidb__pb2.InsertRequest.SerializeToString,
                response_deserializer=akidb__pb2.InsertResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/akidb.v1.Akidb/Search',
                request_serializer=akidb__pb2.SearchRequest.SerializeToString,
                response_deserializer=akidb__pb2.SearchResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/akidb.v1.Akidb/Delete',
                request_serializer=akidb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=akidb__pb2.DeleteResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/akidb.v1.Akidb/Update',
                request_serializer=akidb__pb2.UpdateRequest.SerializeToString,
                response_deserializer=akidb__pb2.UpdateResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/akidb.v1.Akidb/Get',
                request_serializer=akidb__pb2.GetRequest.SerializeToString,
                response_deserializer=akidb__pb2.GetResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/akidb.v1.Akidb/Health',
                request_serializer=akidb__pb2.HealthRequest.SerializeToString,
                response_deserializer=akidb__pb2.HealthResponse.FromString,
                )
        self.InsertBatch = channel.unary_unary(
                '/akidb.v1.Akidb/InsertBatch',
                request_serializer=akidb__pb2.InsertBatchRequest.SerializeToString,
                response_deserializer=akidb__pb2.InsertBatchResponse.FromString,
                )
        self.SearchBatch = channel.unary_unary(
                '/akidb.v1.Akidb/SearchBatch',
                request_serializer=akidb__pb2.SearchBatchRequest.SerializeToString,
                response_deserializer=akidb__pb2.SearchBatchResponse.FromString,
                )
        self.GetClusterState = channel.unary_unary(
                '/akidb.v1.Akidb/GetClusterState',
                request_serializer=akidb__pb2.GetClusterStateRequest.SerializeToString,
                response_deserializer=akidb__pb2.GetClusterStateResponse.FromString,
                )
        self.TextSearch = channel.unary_unary(
                '/akidb.v1.Akidb/TextSearch',
                request_serializer=akidb__pb2.TextSearchRequest.SerializeToString,
                response_deserializer=akidb__pb2.SearchResponse.FromString,
                )


class AkidbServicer(object):
    """AkiDB Vector Database Service
    """

    def Insert(self, request, context):
        """Insert a vector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for similar vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete a vector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Update a vector (upsert semantics)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get a vector by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertBatch(self, request, context):
        """Batch insert
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBatch(self, request, context):
        """Batch search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterState(self, request, context):
        """Get cluster state (coordinators and shards)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextSearch(self, request, context):
        """Text search: embed text via ax-engine, then search for similar vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AkidbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=akidb__pb2.InsertRequest.FromString,
                    response_serializer=akidb__pb2.InsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=akidb__pb2.SearchRequest.FromString,
                    response_serializer=akidb__pb2.SearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=akidb__pb2.DeleteRequest.FromString,
                    response_serializer=akidb__pb2.DeleteResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=akidb__pb2.UpdateRequest.FromString,
                    response_serializer=akidb__pb2.UpdateResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=akidb__pb2.GetRequest.FromString,
                    response_serializer=akidb__pb2.GetResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=akidb__pb2.HealthRequest.FromString,
                    response_serializer=akidb__pb2.HealthResponse.SerializeToString,
            ),
            'InsertBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertBatch,
                    request_deserializer=akidb__pb2.InsertBatchRequest.FromString,
                    response_serializer=akidb__pb2.InsertBatchResponse.SerializeToString,
            ),
            'SearchBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBatch,
                    request_deserializer=akidb__pb2.SearchBatchRequest.FromString,
                    response_serializer=akidb__pb2.SearchBatchResponse.SerializeToString,
            ),
            'GetClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterState,
                    request_deserializer=akidb__pb2.GetClusterStateRequest.FromString,
                    response_serializer=akidb__pb2.GetClusterStateResponse.SerializeToString,
            ),
            'TextSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.TextSearch,
                    request_deserializer=akidb__pb2.TextSearchRequest.FromString,
                    response_serializer=akidb__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akidb.v1.Akidb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Akidb(object):
    """AkiDB Vector Database Service
    """

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/Insert',
            akidb__pb2.InsertRequest.SerializeToString,
            akidb__pb2.InsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/Search',
            akidb__pb2.SearchRequest.SerializeToString,
            akidb__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/Delete',
            akidb__pb2.DeleteRequest.SerializeToString,
            akidb__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/Update',
            akidb__pb2.UpdateRequest.SerializeToString,
            akidb__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/Get',
            akidb__pb2.GetRequest.SerializeToString,
            akidb__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/Health',
            akidb__pb2.HealthRequest.SerializeToString,
            akidb__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/InsertBatch',
            akidb__pb2.InsertBatchRequest.SerializeToString,
            akidb__pb2.InsertBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/SearchBatch',
            akidb__pb2.SearchBatchRequest.SerializeToString,
            akidb__pb2.SearchBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/GetClusterState',
            akidb__pb2.GetClusterStateRequest.SerializeToString,
            akidb__pb2.GetClusterStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TextSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.Akidb/TextSearch',
            akidb__pb2.TextSearchRequest.SerializeToString,
            akidb__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class IngestionServiceStub(object):
    """============================================
    Ingestion Service
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerSync = channel.unary_unary(
                '/akidb.v1.IngestionService/TriggerSync',
                request_serializer=akidb__pb2.TriggerSyncRequest.SerializeToString,
                response_deserializer=akidb__pb2.TriggerSyncResponse.FromString,
                )
        self.GetSyncStatus = channel.unary_unary(
                '/akidb.v1.IngestionService/GetSyncStatus',
                request_serializer=akidb__pb2.GetSyncStatusRequest.SerializeToString,
                response_deserializer=akidb__pb2.SyncStatusResponse.FromString,
                )
        self.UpdateTags = channel.unary_unary(
                '/akidb.v1.IngestionService/UpdateTags',
                request_serializer=akidb__pb2.UpdateTagsRequest.SerializeToString,
                response_deserializer=akidb__pb2.UpdateTagsResponse.FromString,
                )
        self.ReindexCategory = channel.unary_unary(
                '/akidb.v1.IngestionService/ReindexCategory',
                request_serializer=akidb__pb2.ReindexCategoryRequest.SerializeToString,
                response_deserializer=akidb__pb2.ReindexCategoryResponse.FromString,
                )
        self.DeleteCategory = channel.unary_unary(
                '/akidb.v1.IngestionService/DeleteCategory',
                request_serializer=akidb__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=akidb__pb2.DeleteCategoryResponse.FromString,
                )
        self.ListCategories = channel.unary_unary(
                '/akidb.v1.IngestionService/ListCategories',
                request_serializer=akidb__pb2.ListCategoriesRequest.SerializeToString,
                response_deserializer=akidb__pb2.ListCategoriesResponse.FromString,
                )


class IngestionServiceServicer(object):
    """============================================
    Ingestion Service
    ============================================

    """

    def TriggerSync(self, request, context):
        """Trigger a sync run manually
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncStatus(self, request, context):
        """Get sync status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTags(self, request, context):
        """Update tags on existing documents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReindexCategory(self, request, context):
        """Reindex a category
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Delete a category (soft or hard)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategories(self, request, context):
        """List categories
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerSync': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSync,
                    request_deserializer=akidb__pb2.TriggerSyncRequest.FromString,
                    response_serializer=akidb__pb2.TriggerSyncResponse.SerializeToString,
            ),
            'GetSyncStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncStatus,
                    request_deserializer=akidb__pb2.GetSyncStatusRequest.FromString,
                    response_serializer=akidb__pb2.SyncStatusResponse.SerializeToString,
            ),
            'UpdateTags': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTags,
                    request_deserializer=akidb__pb2.UpdateTagsRequest.FromString,
                    response_serializer=akidb__pb2.UpdateTagsResponse.SerializeToString,
            ),
            'ReindexCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.ReindexCategory,
                    request_deserializer=akidb__pb2.ReindexCategoryRequest.FromString,
                    response_serializer=akidb__pb2.ReindexCategoryResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=akidb__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=akidb__pb2.DeleteCategoryResponse.SerializeToString,
            ),
            'ListCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategories,
                    request_deserializer=akidb__pb2.ListCategoriesRequest.FromString,
                    response_serializer=akidb__pb2.ListCategoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akidb.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """============================================
    Ingestion Service
    ============================================

    """

    @staticmethod
    def TriggerSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.IngestionService/TriggerSync',
            akidb__pb2.TriggerSyncRequest.SerializeToString,
            akidb__pb2.TriggerSyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSyncStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.IngestionService/GetSyncStatus',
            akidb__pb2.GetSyncStatusRequest.SerializeToString,
            akidb__pb2.SyncStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.IngestionService/UpdateTags',
            akidb__pb2.UpdateTagsRequest.SerializeToString,
            akidb__pb2.UpdateTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReindexCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.IngestionService/ReindexCategory',
            akidb__pb2.ReindexCategoryRequest.SerializeToString,
            akidb__pb2.ReindexCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.IngestionService/DeleteCategory',
            akidb__pb2.DeleteCategoryRequest.SerializeToString,
            akidb__pb2.DeleteCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.IngestionService/ListCategories',
            akidb__pb2.ListCategoriesRequest.SerializeToString,
            akidb__pb2.ListCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AdminServiceStub(object):
    """============================================
    Admin Service - Background Task Management
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBackgroundTaskStatus = channel.unary_unary(
                '/akidb.v1.AdminService/GetBackgroundTaskStatus',
                request_serializer=akidb__pb2.GetBackgroundTaskStatusRequest.SerializeToString,
                response_deserializer=akidb__pb2.GetBackgroundTaskStatusResponse.FromString,
                )
        self.GetTaskHistory = channel.unary_unary(
                '/akidb.v1.AdminService/GetTaskHistory',
                request_serializer=akidb__pb2.GetTaskHistoryRequest.SerializeToString,
                response_deserializer=akidb__pb2.GetTaskHistoryResponse.FromString,
                )
        self.TriggerSnapshot = channel.unary_unary(
                '/akidb.v1.AdminService/TriggerSnapshot',
                request_serializer=akidb__pb2.TriggerSnapshotRequest.SerializeToString,
                response_deserializer=akidb__pb2.TriggerSnapshotResponse.FromString,
                )
        self.TriggerRebuild = channel.unary_unary(
                '/akidb.v1.AdminService/TriggerRebuild',
                request_serializer=akidb__pb2.TriggerRebuildRequest.SerializeToString,
                response_deserializer=akidb__pb2.TriggerRebuildResponse.FromString,
                )
        self.CancelTask = channel.unary_unary(
                '/akidb.v1.AdminService/CancelTask',
                request_serializer=akidb__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=akidb__pb2.CancelTaskResponse.FromString,
                )
        self.GetResourceStatus = channel.unary_unary(
                '/akidb.v1.AdminService/GetResourceStatus',
                request_serializer=akidb__pb2.GetResourceStatusRequest.SerializeToString,
                response_deserializer=akidb__pb2.GetResourceStatusResponse.FromString,
                )
        self.ConfigureWebhook = channel.unary_unary(
                '/akidb.v1.AdminService/ConfigureWebhook',
                request_serializer=akidb__pb2.ConfigureWebhookRequest.SerializeToString,
                response_deserializer=akidb__pb2.ConfigureWebhookResponse.FromString,
                )
        self.GetWebhookConfig = channel.unary_unary(
                '/akidb.v1.AdminService/GetWebhookConfig',
                request_serializer=akidb__pb2.GetWebhookConfigRequest.SerializeToString,
                response_deserializer=akidb__pb2.GetWebhookConfigResponse.FromString,
                )


class AdminServiceServicer(object):
    """============================================
    Admin Service - Background Task Management
    ============================================

    """

    def GetBackgroundTaskStatus(self, request, context):
        """Get status of all background tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskHistory(self, request, context):
        """List task execution history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSnapshot(self, request, context):
        """Trigger a snapshot manually
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerRebuild(self, request, context):
        """Trigger an index rebuild manually
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Cancel a running task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceStatus(self, request, context):
        """Get resource governor status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureWebhook(self, request, context):
        """Configure webhook alerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebhookConfig(self, request, context):
        """Get current webhook configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBackgroundTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackgroundTaskStatus,
                    request_deserializer=akidb__pb2.GetBackgroundTaskStatusRequest.FromString,
                    response_serializer=akidb__pb2.GetBackgroundTaskStatusResponse.SerializeToString,
            ),
            'GetTaskHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskHistory,
                    request_deserializer=akidb__pb2.GetTaskHistoryRequest.FromString,
                    response_serializer=akidb__pb2.GetTaskHistoryResponse.SerializeToString,
            ),
            'TriggerSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSnapshot,
                    request_deserializer=akidb__pb2.TriggerSnapshotRequest.FromString,
                    response_serializer=akidb__pb2.TriggerSnapshotResponse.SerializeToString,
            ),
            'TriggerRebuild': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRebuild,
                    request_deserializer=akidb__pb2.TriggerRebuildRequest.FromString,
                    response_serializer=akidb__pb2.TriggerRebuildResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=akidb__pb2.CancelTaskRequest.FromString,
                    response_serializer=akidb__pb2.CancelTaskResponse.SerializeToString,
            ),
            'GetResourceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceStatus,
                    request_deserializer=akidb__pb2.GetResourceStatusRequest.FromString,
                    response_serializer=akidb__pb2.GetResourceStatusResponse.SerializeToString,
            ),
            'ConfigureWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureWebhook,
                    request_deserializer=akidb__pb2.ConfigureWebhookRequest.FromString,
                    response_serializer=akidb__pb2.ConfigureWebhookResponse.SerializeToString,
            ),
            'GetWebhookConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebhookConfig,
                    request_deserializer=akidb__pb2.GetWebhookConfigRequest.FromString,
                    response_serializer=akidb__pb2.GetWebhookConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akidb.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """============================================
    Admin Service - Background Task Management
    ============================================

    """

    @staticmethod
    def GetBackgroundTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/GetBackgroundTaskStatus',
            akidb__pb2.GetBackgroundTaskStatusRequest.SerializeToString,
            akidb__pb2.GetBackgroundTaskStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/GetTaskHistory',
            akidb__pb2.GetTaskHistoryRequest.SerializeToString,
            akidb__pb2.GetTaskHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/TriggerSnapshot',
            akidb__pb2.TriggerSnapshotRequest.SerializeToString,
            akidb__pb2.TriggerSnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerRebuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/TriggerRebuild',
            akidb__pb2.TriggerRebuildRequest.SerializeToString,
            akidb__pb2.TriggerRebuildResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/CancelTask',
            akidb__pb2.CancelTaskRequest.SerializeToString,
            akidb__pb2.CancelTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResourceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/GetResourceStatus',
            akidb__pb2.GetResourceStatusRequest.SerializeToString,
            akidb__pb2.GetResourceStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/ConfigureWebhook',
            akidb__pb2.ConfigureWebhookRequest.SerializeToString,
            akidb__pb2.ConfigureWebhookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWebhookConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/akidb.v1.AdminService/GetWebhookConfig',
            akidb__pb2.GetWebhookConfigRequest.SerializeToString,
            akidb__pb2.GetWebhookConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
