---
all:
  vars:
    ansible_user: root
  children:
    akidb_cluster:
      vars:
        akidb_cluster_network_trusted: true
      children:
        akidb_shards:
          hosts:
            akidb-1:
              ansible_host: 192.0.2.11
              akidb_overlay_address: 10.77.0.11
            akidb-2:
              ansible_host: 192.0.2.12
              akidb_overlay_address: 10.77.0.12
            akidb-3:
              ansible_host: 192.0.2.13
              akidb_overlay_address: 10.77.0.13
            akidb-4:
              ansible_host: 192.0.2.14
              akidb_overlay_address: 10.77.0.14
        akidb_coordinators:
          hosts:
            akidb-1:
